### ISSUE TITLE
icoontjes links zijn onduidelijk

### ISSUE THREAD

**Issue by christianvriens** [humanswitch/consentcookie#1]
Veelbelovend maar nog niet helemaal duidelijk genoeg. De icoontjes links in de popup zijn (voor mij) nietszeggend op dit moment. Dit zou veel duidelijker moeten zijn wat de verschillende soorten cookies zijn. Misschien gewoon textueel voor te stellen ipv aan de hand van iconen.

**Comment by StevenChoo** [comment]
Agree. Will pick this up.

Will replace the icons with the name of the trackers / applications based on the consentcookie resource file.

**Comment by StevenChoo** [comment]
Added the fix on the dev branch

**Comment by StevenChoo** [comment]
updated design.

![image](https://user-images.githubusercontent.com/8590349/39587137-1709614c-4ef9-11e8-96c2-7579ac75971a.png)
