### ISSUE TITLE
transparent icon not rendered well after opening ConsentCookie

### ISSUE THREAD

**Issue by rockxwre** [humanswitch/consentcookie#18]
## Description
I configured ConsentCookie with an almost transparent secondary color.
![screenshot from 2018-04-12 11 25 46](https://user-images.githubusercontent.com/681893/38668462-4ab9a56c-3e44-11e8-9a25-3f66ac2fef41.png)
## Expected Behavior
The whole circle should be transparent.
## Steps to Reproduce
Configure ConsentCookie using:
```
window.ConsentCookie.init({"apps":{"endpoint":"https://www.consentcookie.nl/consentcookie/latest/consentcookie.json","consent":{"cc":{"initstate":"optin"},"gtm":{"initstate":"optin"}}},"design":{"layout":{"position":"right"},"colorscheme":{"primary":"#6DFC90","secondary":"rgba(157,32,119,0.02)","tertiary":"#2C612B"}},"resources":{"nl":{"info":{"title":"Over ConsentCookie","text":""}}}});
    if (true) {
}
```
## Your Environment
* Firefox 59.0.2

**Comment by StevenChoo** [comment]
This is not an bug, but related to how css works. To have the menu "slide in" it needs to go behind something. The menu button is circular and the menu has rounded corners so to have it fully disappear it needs to go behind the menu button. If the menu button is transparent you will see the menu behind it.
