### ISSUE TITLE
List of trackers returns a 404

### ISSUE THREAD

**Issue by FreDeRoover** [humanswitch/consentcookie#20]
## Description

The link to the trackers within the readme redirects to https://github.com/humanswitch/consentcookie/blob/master/src/assets/json/trackers.json, which is a 404 page

## Steps to Reproduce

1. Go to https://github.com/humanswitch/consentcookie#consentcookieinit
2. Click on ConsentCookie tracker list

**Comment by StevenChoo** [comment]
Thank you for reporting this. 

With version 0.6 we removed the trackers from the build itself and its now loaded as a separate resource. The current list is available in the [dist](https://github.com/humanswitch/consentcookie/blob/master/dist/consentcookie.json) folder.

I will make an issue to update the documentation with the changes related to 0.6.
