### ISSUE TITLE
Alwayson tracker toggle shows 'off' instead of on

### ISSUE THREAD

**Issue by StevenChoo** [humanswitch/consentcookie#41]
## Description
![image](https://user-images.githubusercontent.com/8590349/40471593-664b9dee-5f37-11e8-9b07-9ca178fd45b8.png)

## Expected Behavior
In the demo, shown in the screenshot, the Google Tag Manager and IQNOMY the toggle should be disabled but shown as 'on'

![image](https://user-images.githubusercontent.com/8590349/40476207-c11681f6-5f43-11e8-81c0-097c36b0c882.png)

## Actual Behavior
The toggles value is set 'off'

## Possible Fix
n.a.

## Steps to Reproduce
1. configure ConsentCookie with a always on application
2. open application view 

## Context
It is showing the wrong state

## Your Environment
* All enviroments

**Comment by StevenChoo** [comment]
@christianvriens Could you check the bug fix.

http://cdn.humanswitch.services/cc/consentcookie/app/snapshot/4689c71658b8fc78bcdb4976f4be00a4e6528b7d/consentcookie.min.js

**Comment by christianvriens** [comment]
Tested

Is solved!
