### ISSUE TITLE
ConsentCookie API changes #23 regression bug

### ISSUE THREAD

**Issue by StevenChoo** [humanswitch/consentcookie#44]
## Description
Return of ConsentCookie.get() does not contain a public variables ```consents``` with the key-value mapping of the Consents mapped by the id

## Expected Behavior
![image](https://user-images.githubusercontent.com/8590349/40479786-d384c056-5f4c-11e8-9035-d2bfdd1b2ae8.png)

## Actual Behavior

![image](https://user-images.githubusercontent.com/8590349/40479823-f5ead360-5f4c-11e8-8585-2c6352eee0e0.png)

## Possible Fix
Make the API backwards compatible with 0.6.4

## Steps to Reproduce
1. load the demo page
2. from console after ConsentCookie has been initialized: ConsentCookie.get()

## Context
GTM implementation does not work properly

## Your Environment
n.a.

**Comment by StevenChoo** [comment]
Fixed backwards compatibility

![image](https://user-images.githubusercontent.com/8590349/40480187-ff07fada-5f4d-11e8-8885-d0080566b2bb.png)

@christianvriens Could you confirm this:

https://cdn.humanswitch.services/cc/consentcookie/app/snapshot/adc70bf05e62049cfe388fcb56b377bb8a91ebb1/consentcookie.min.js

**Comment by christianvriens** [comment]
Tested

Is solved!
