### ISSUE TITLE
Where is the tracker list?

### ISSUE THREAD

**Issue by posttoast** [humanswitch/consentcookie#53]
I'm looking for the tracker-list which, according to the documentation, is supposed to be found at https://github.com/humanswitch/consentcookie/blob/master/src/assets/json/trackers.json. This file does not exist though...

**Comment by StevenChoo** [comment]
We removed the tracker list from the ConsentCookie project and its now maintained externally.

For the moment you can get the latest version at: [link](http://cdn.humanswitch.services/cc/consentcookie/consentcookie.json)

Also it it possible to make use of our [configurator](https://www.consentcookie.nl/configuratie/) tool to get an better overview which applications are available and you can submit any missing application.

Documentation is currently be updated with this info.
