### ISSUE TITLE
Set default language through CC API

### ISSUE THREAD

**Issue by christianvriens** [humanswitch/consentcookie#57]
## Description
This options is very handy for multi language websites. The consent cookie can then automaticly be set by the website to the default language. 

## Expected Behavior
Is described in #55.

**Comment by StevenChoo** [comment]
@christianvriens This is already implemented but not yet documented.

You can use the following to set the language. It works reactively

```javascript
// Premise is ConsentCookie is initialized and available as global object.
// Change language to 'en'
ConsentCookie.setLanguage('en');
// Language is inmediatly changed to 'en' and the resources configured in the config with key 'en' are used.
```

**Comment by christianvriens** [comment]
Documentation is added on CC website: https://www.consentcookie.nl/doc/consentcookie/technische-documentatie/#5811
